# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Blog
tagline:             ''
description:         ''
url:                 http://weihan.online
baseurl:             http://weihan.online/blog/lanyon/_site/
paginate:            5

# About/contact
author:
  name:              Weihan Jiang
  url:               http://weihan.online
  email:             theweihanjiang@gmail.com

# Custom vars
version:             1.0.0


gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"